server:
  port: 10080
  error:
    path: '/error'
spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8
  data:
    mongodb:
      # k8s 내부
      #uri: mongodb://mongodb-headless.mongodb.svc.cluster.local:27017/service
      # local
      uri: mongodb://localhost:27017/service